# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slivi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='captcha_image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Captcha Image'),
        ),
    ]
