# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slivi', '0002_auto_20171213_1257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='captcha',
            name='captcha_image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
