# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-08 14:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('captcha_text', models.CharField(max_length=5)),
                ('captcha_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
